### ISSUE TITLE
Toggle chats?

### ISSUE THREAD

**Issue by Calluhm** [ryans1230/BungeeChatChannels#1]
Hey mate, wondering if you could add a way to toggle the channels on/off so people didnt need to imput a command everytime. Thanks

**Comment by ryans1230** [comment]
The details are in the commit message, but I'll explain here as well. It first must be enabled in the configuration. 'noCommand' can be added under toggles, or delete the config file to generate a new one (off by default). 

Usage is the command with no arguments. The same command again is to disable it and return to whatever you server chat plugin is.

**Comment by Calluhm** [comment]
Thanks for the response. I've added the "noCommand" option to the config + updated the plugin. Toggling the chat on seems to break chat completely though, I cannot even type commands

**Comment by Calluhm** [comment]
Quick fix for the commands, but toggling the chat still doesn't allow you to talk in the chat and there is no way to toggle it off. Also, NO_CMD cannot be changed ingame as of yet

**Comment by Calluhm** [comment]
Ok thanks a lot for updating the so quickly for me, I really appreciate it. Everything seems to be working a lot smoother now apart from the fact that when channels are toggled on your message is sent to both the main chat and the channel chat.

**Comment by ryans1230** [comment]
That must be a plugin issue on your end. I tested with default chat and it works as intended. Because this operates at the Proxy level, there is a chance that the server can pick up the chat before the event is cancelled at the Proxy level

**Comment by Calluhm** [comment]
Would you suggest anything to fix that? The server I am using it on it running deluxechat so it may be interfering with that

**Comment by ryans1230** [comment]
Are you running DeluxeChat on the BungeeCord, or just the servers? In theory, one would think that the BungeeCord chat event, but I am cancelling it when conditions are met, so I'm not sure how DeluxeChat can get it if it's on the downstream server

**Comment by Calluhm** [comment]
Running DeluxeChat on bungeecord, with all chats going into one global.

**Comment by ryans1230** [comment]
That's probably why. If you want you can fork this project, and add `(priority = EventHandler.HIGHEST)` in the listener class after `@EventHandler` to try to prevent it from happening.

**Comment by Calluhm** [comment]
Could you talk me through how to do that? if you dont mind

**Comment by ryans1230** [comment]
Try this file: https://drive.google.com/open?id=0B2Io45pOR50tb2UwejM1UVFpSlU

**Comment by Calluhm** [comment]
Fixed toggle chats for everything apart from /sc I can go without that if you dont want to update again. Amazing job with getting these updates out so fast

**Comment by ryans1230** [comment]
You can redownload the file again, gotta love Google Drive and their version :)

**Comment by Calluhm** [comment]
Much love pal <3

**Comment by Calluhm** [comment]
Everything's working great in the latest update, could you add the option of editing the toggle messages for chats too?
